- menu_name: "Länkar"

- name: "Köp boken här"
  url: "https://enhandbok.store/"
  title: "Köp boken här"

- name: "Kontakt"
  url: "/kontakt/"
  title: "Kontakt"

- name: "Instagram"
  url: "https://Instagram.com/enhandbok"
  title: "Instagram"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"
#
#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
